### ISSUE TITLE
OSHWA certification

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-hardware#11]
I just had a quick look for AYAB here and couldn't find it. Let's register! I'd love to put a OSHW logo on the next batch of boards that I make :)

https://certification.oshwa.org/list.html

**Comment by chris007de** [comment]
Sure :) Who's gonna do it? As the Shield v2 is EMSL's contribution, I'd propose @oskay  - would you be Ok with that?

**Comment by VIPQualityPost** [comment]
We can finally mark this one done 😀
