### ISSUE TITLE
Output impedance of Hall sensors

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-hardware#13]
Has anyone measured it? I imagine it is buffered by a LM358.

**Comment by VIPQualityPost** [comment]
Was there a concern associated with this? 
New design is hi-z / buffered anyway so no issue with loading for the new boards at least.

**Comment by t0mpr1c3** [comment]
I think my original concern might have been that the output from the Hall sensor might be a floating collector from a comparator, in which case you would need a pull up.
