### ISSUE TITLE
Connectors for Brother CK-35

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-hardware#16]
The software claims to run on CK-35. Does the Shieldv2 have the right connectors for it?

**Comment by chris007de** [comment]
I'll inquire at somebody who might know about this and put you on CC :)

**Comment by VIPQualityPost** [comment]
Victoria remarks that it is the same as KH900, 965, so we are set : https://discord.com/channels/1079442610332110849/1087758789303865394/1157259185537429514

**Comment by t0mpr1c3** [comment]
Amazing that she actually has one
