### ISSUE TITLE
Correct right hall sensor detection

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-hardware#19]
see https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/51#issuecomment-1467086056 and following

**Comment by VIPQualityPost** [comment]
So what is the resolution to this?
Do we want to have two input pins for 910 EOL, one for K and one for L? 
Or should we just OR the two signals, because we can sense if the carriage has moved >3 needles but shows a pulse longer than single magnet?

maybe we can get some comments from @jpcornil-git

**Comment by jpcornil-git** [comment]
I would use both (digital) inputs to avoid another (less robust ?) detection mechanism for LKG carriages.

One input is indeed equivalent to "hallValue < FILTER_R_MIN" and the other to "hallValue > FILTER_R_MAX" and existing code can therefore easily be modified to cope with this.

**Comment by jpcornil-git** [comment]
I would use both (digital) inputs to avoid another (less robust ?) detection mechanism for LKG carriages.

One input is indeed equivalent to "hallValue < FILTER_R_MIN" and the other to "hallValue > FILTER_R_MAX" and existing code can therefore easily be modified to cope with this.

**Comment by jpcornil-git** [comment]
... and you can't differentiate K and L anymore with an OR approach (one short pulse for both) -> not an option anyway

**Comment by VIPQualityPost** [comment]
Right, I was thinking because they are a pulse that you can do it, but it doesn't work for other machines anyway. It will have it's own pin.

**Comment by VIPQualityPost** [comment]
We did it!
