### ISSUE TITLE
Shield V2 Footprints U2 and U3 in Gerber files do not match SSOP20

### ISSUE THREAD

**Issue by atrophy** [AllYarnsAreBeautiful/ayab-hardware#5]
The footprints on the current version of the Gerber files don't match the SSOP20 part listed in the BOM. Should we be using the SOIC version of the PCF8574?

![IMG_20190808_115813](https://user-images.githubusercontent.com/729522/62665593-05061200-b9d4-11e9-8e4c-74d189acb22a.jpg)

**Comment by oskay** [comment]
Yes, looks like that's an error on the BOM.

**Comment by oskay** [comment]
Are you fabricating boards to sell?

**Comment by atrophy** [comment]
Not to sell no, I work at Fab Lab Wgtn, part of Massey University and we're converting a couple of the university's knitting machines over to use in the lab.

**Comment by oskay** [comment]
(That's fine -- we're still hoping to find someone happy to make and sell a batch.)

**Comment by chris007de** [comment]
Thanks a lot for fixing this issue!
